boostcampwm-2022/web06-weview

client/jest.config.js
client/package-lock.json
client/package.json

- `npm run test` 명령어로 Jest 테스트를 진행할 수 있도록 프로젝트에 테스트 환경 설정
- related #8 

FE Jest 테스트 환경 구축 (#8)

---

client/package-lock.json
client/package.json
client/src/App.tsx
client/src/index.css
client/src/main.tsx
client/src/store/useBearStore.ts

클라이언트 전역 상태관리 라이브러리로 zustand를 선택하여 적용하고 예시 코드를 만들어보았습니다.
-  interface 이름은 `해당내용Store` 형식 
- ex: `BearStore`
- 내보내는 store hook 이름은 `use해당내용Store` 형식
- ex: `useBearStore`
- 
(fix #일이삼)
#11 

FE zustand 세팅 및 환경 구축 (#11) 

---

client/package-lock.json
client/package.json
client/src/App.tsx
client/src/main.tsx

서버 상태관리 라이브러리로 `react query`를 선택하여 적용했습니다.
또한 디버깅을 위한 `devtools` 를 함께 적용했습니다.
실행 도중 `useBearStore` 파일 import 경로가 올바르지 않은 버그가 있어서 수정했습니다.
- related #11 

FE react query 세팅 및 환경 구축 (#11)

---

.github/workflows/dev-client-deploy.yml
.github/workflows/dev-server-deploy.yml

개발서버용 클라이언트 자동 배포 github action 적용
- related #12

ci(DO): 개발서버 자동 배포 적용 (#12)

---

client/.husky/commit-msg
client/.husky/pre-commit
client/package-lock.json
client/package.json
server/.husky/commit-msg
server/.husky/pre-commit
server/package-lock.json
server/package.json

husky 설정 추가 위해 FE, BE 스크립트 작성 및 환경 설정
client나 server폴더에서 개발한 후 `git add` 이후 `git commit` 이나 `git cz` 입력하면 진행됩니다.
추가하고 싶으신 설정이 있다면 npm 관련 명령어를 추가하시면 문제없이 동작할 것 입니다.
혹은 저한테 특정 세팅을 부탁하시면 알아보겠습니다.
- related #13

CI 커밋 hooks관련 husky 설정 추가 (#13)

---

client/package-lock.json

- husky 설정으로 생긴 package-lock.json 업데이트가 미반영 된 문제 해결
- related #24 

package-lock.json에 husky 세부 정보 업데이트 (#24)

---

.github/workflows/dev-client-deploy.yml
.github/workflows/dev-server-deploy.yml
server/Dockerfile

깃허브 액션 CD 스크립트 수정 및 오류 수정
(fix #일이삼)
- related #24 

Fix/#24 깃허브 액션 CD 스크립트 수정 및 오류 수정

---

.github/workflows/client-integration.yml
.github/workflows/server-integration.yml

프론트와 백을 분리해서 Pull Request 전에 Build, Test를 실행한다
- related #31 

CI 테스트 환경 구축 (#31)

---

README.md

- README.md 추가
- 프로젝트 소개, 팀원 소개, 프로세스, 기술 스택, 바로가기 링크 작성
- related #33 

README.md 추가 및 내용 작성 (#33)

---

client/.gitignore
client/package-lock.json
client/package.json
client/src/apis/auth.ts
client/src/apis/axios.ts
client/src/apis/interceptors/refresh.ts
client/src/env.d.ts
client/src/types/auth.ts
client/src/utils/localStorage.ts

OAuth api 추가후 token refresh handler 추가하였습니다.
`.env.local`을 추가하였습니다.
이는 개인적으로 공유하겠습니다.
- related #19 

OAuth api 추가후 token refresh handler 추가하였습니다.

---

client/constants/mode.ts
client/package-lock.json
client/package.json
client/public/mockServiceWorker.js
client/src/apis/auth.ts
client/src/components/Profile/NotLoggedInProfile/NotLoggedInProfile.tsx
client/src/main.tsx
client/src/mocks/browser.ts
client/src/mocks/handlers.ts
client/src/mocks/mockData.ts
client/src/mocks/server.ts
client/src/setUpTest.ts
client/src/utils/localStorage.ts

- react hook unit test를 위한 모킹 세팅을 추가했습니다.
- 실제 서버 로직이 완성되기 전에 mock된 API 요청을 보내기 위해 브라우저 mock 세팅을 완료했습니다.
- 로컬스토리지 버그 수정하였습니다.
- related #42

msw 서버 데이터 모킹 세팅 추가 (#42)

---

server/.gitignore
server/package-lock.json
server/package.json
server/src/app.module.ts
server/src/domain/base-time.entity.ts
server/src/domain/post/post.entity.ts
server/src/domain/user/user.entity.ts

- TypeORM을 사용해 DB 연결
- User, Post, BaseTimeEntity 엔티티 생성
- related #43 

Database 연결 (#43)

---

server/package-lock.json
server/package.json
server/src/app.module.ts
server/src/auth/auth.controller.spec.ts
server/src/auth/auth.controller.ts
server/src/auth/auth.module.ts
server/src/auth/auth.service.spec.ts
server/src/auth/auth.service.ts

- github oauth를 axios 라이브러리로 구현했습니다.
- related #5 

github oauth를 axios 라이브러리로 구현했습니다.

---

server/package-lock.json
server/package.json
server/src/auth/auth.controller.ts
server/src/auth/auth.module.ts
server/src/auth/auth.service.spec.ts
server/src/auth/auth.service.ts
server/src/domain/user/user.entity.ts

AuthService 레이어에서 회원에 대해 토큰을 발급합니다
- related #56 

회원에 대해 인증한 뒤 토큰 발급 기능 구현

---

server/src/domain/auth/auth.controller.ts
server/src/domain/auth/auth.service.ts
server/src/domain/auth/dto/controller-response.dto.ts
server/src/domain/base-time.entity.ts

API 명세 변경에 따라 서버에서 리턴하는 값의 양식을 변경했습니다.
- related #67 

API 명세 변경에 따라 서버 리턴값을 변경했습니다.

---

server/src/domain/post/post.controller.spec.ts
server/src/domain/post/post.controller.ts
server/src/domain/post/post.module.ts
server/src/domain/post/post.service.spec.ts
server/src/domain/post/post.service.ts

- 게시물 엔티티 구조를 생성했습니다.
- related #69 

게시물 엔티티 구조를 생성했습니다.

---

client/src/components/PostBar/Post/Post.scss
client/src/components/PostBar/Post/Post.tsx
client/src/components/PostBar/PostBar.scss
client/src/components/PostBar/PostBar.tsx
client/src/hooks/useRelativeSize.tsx
client/src/mocks/handlers/postHandler.ts
client/src/mocks/mockData.ts
client/src/types/post.ts

- useRelativeSize 커스텀 훅을 통해 minWidth, minHeight, 그리고 가로 대비 세로 비율 (heightRatio) 를 입력해서 PostBar가 반응형으로 크기가 변하도록 구현
- related #60 

PostBar에 반응형 UI 적용 (#60)

---

client/src/components/PostBar/Post/Post.scss
client/src/components/PostBar/Post/PostSummary/CodeInfo/CodeInfo.tsx
client/src/components/PostBar/PostBar.scss
client/src/utils/regExpression.ts

- constants 경로 변경 적용
- regExpression에 정규표현식 이동
- related #82

constants 폴더 경로 오류 수정 및 정규표현식 코드 정리 (#82)

---

client/src/App.scss
client/src/App.tsx
client/src/ReactRouter.tsx
client/src/components/CommonButtons/CommonButtons.scss
client/src/components/MainNav/Filter/Filter.scss
client/src/components/MainNav/MainNav.scss
client/src/components/MainNav/Menu/Menu.scss
client/src/components/MainNav/Profile/NotLoggedInProfile/NotLoggedInProfile.scss
client/src/components/MainNav/Profile/NotLoggedInProfile/NotLoggedInProfile.tsx
client/src/components/MainNav/Profile/Profile.scss
client/src/components/MainNav/Profile/Profile.tsx
client/src/components/MainNav/Profile/UserProfile/UserProfile.scss
client/src/components/MainNav/Profile/UserProfile/UserProfile.tsx
client/src/pages/LoginCallback/LoginCallback.scss
client/src/pages/Main/Main.scss
client/src/pages/Main/Main.tsx

nav 레이아웃을 잡고 page를 분리하여 메인페이지 레이아웃을 정리하였습니다.
- related #86 
- related #91

전역 레이아웃에서 page를 분리하고 nav 레이아웃을 스타일링했습니다.

---

client/src/components/WriteModal/SubmitModal/SubmitModal.tsx
client/src/components/WriteModal/SubmitModal/TagInput/TagInput.tsx
client/src/store/useWritingStore.ts
client/src/utils/pressedKeyCheck.ts
client/src/utils/regExpression.ts

태그 포매팅 및 삭제 기능 추가하였습니다.
- related #85 

feat(FE): 태그 포매팅 기능 및 삭제 기능 추가 (#85)

---

server/package.json
server/src/domain/auth/auth.module.ts
server/src/domain/post/post.module.ts
server/src/domain/post/post.service.spec.ts
server/test/auth.e2e-spec.ts
server/test/post.e2e-spec.ts

- 글 작성 기능에 대한 e2e 테스트를 작성했습니다.
- 인증 e2e 테스트에서 토큰 로직을 개선했습니다.
- `npm run test:e2e` 명령어가 원인과 출력문을 보여주도록 수정했습니다.
- related #97 

글 작성 기능에 대한 e2e 테스트를 작성했습니다.

---

server/src/domain/post/dto/service-response.dto.ts
server/src/domain/post/post.controller.ts
server/src/domain/post/post.entity.ts
server/src/domain/post/post.service.ts

- 게시물 목록 조회 시 각 게시물의 태그ID, 이미지, author를 불러옵니다.
- isLiked 라는 속성은 임시로 true를 넣어줬습니다.
- related #6 
- related #73 

(2차) 게시물 목록을 조회하는 기능을 구현했습니다.

---

server/Dockerfile

- Dockerfile에서 husky 실행 제외
- related #104 

fix(DO): 도커 이미지 업로드에서 husky 동작하는 버그 수정 (#104)

---

.github/workflows/dev-client-deploy.yml

- 프론트엔드 배포 시 환경변수를 생성합니다.
- related #104 

ci(DO): 환경변수 주입 (#104)

---

server/src/domain/post/dto/service-response.dto.ts

글 목록 조회 API 스펙을 클라이언트와 동기화했습니다.
- related #111 

fix(BE): 글 목록 조회 API 스펙 클라이언트와 동기화 (#111)

---

client/src/components/MainNav/Profile/NotLoggedInProfile/NotLoggedInProfile.tsx
client/src/components/MainNav/Profile/UserProfile/UserProfile.tsx
server/src/domain/auth/auth.controller.ts

axios default 헤더를 추가하였습니다.
토큰 삭제 로직도 추가하였습니다.
- related #113

axios 헤더에 토큰이 붙지 않는 에러를 수정하였습니다.

---

client/src/pages/LoginCallback/LoginCallback.tsx

css import 위치 수정했습니다.
- related #107

fix(FE): css import 위치 수정 (#107)

---

client/src/components/MainNav/Profile/NotLoggedInProfile/NotLoggedInProfile.tsx

Authorization 헤더에 Bearer 추가
- related #113 

fix(FE): axios authorization header에 Bearer 추가 (#113)

---

server/src/domain/post/post.service.ts

태그가 없을 때 글 작성에 실패하는 버그를 수정했습니다.
- related #118 

fix(BE): 태그가 없을 때 글 작성 실패하는 버그 수정 (#118)

---

client/src/apis/interceptors/refresh.ts

새로고침 시 액세스 토큰이 사라지는 문제와 refresh 에러 핸들링 관련해서 store를 비우고 header를 지우는 코드를 작성했습니다.
- related #120 

새로고침 시 액세스 토큰 사라짐 문제 해결 및 refresh 에러 핸들링 (#120)

---

client/src/components/WriteModal/SnapShotNav/SnapShotNav.scss
client/src/components/WriteModal/SubmitModal/RegisterButton/RegisterButton.tsx
client/src/components/WriteModal/WriteModal.scss
client/src/components/WriteModal/WritingForm/WritingForm.scss

코드 에디팅 모달을 모바일 뷰에서 보게 될 때를 고려해서 스타일링하였습니다.
- related #123

코드 에디팅 모달 모바일 뷰 스타일링하였습니다.

---

server/src/domain/post/dto/controller-request.dto.ts
server/src/domain/post/dto/service-request.dto.ts
server/src/domain/post/post.controller.ts
server/src/domain/post/post.repository.ts
server/src/domain/post/post.service.spec.ts
server/src/domain/post/post.service.ts
server/test/post.e2e-spec.ts

검색어를 사용해 제목, 내용의 정보를 검색할 수 있게 한다
- related #135 

검색 기능을 구현한다

---

client/src/App.scss
client/src/App.tsx
client/src/components/MainNav/Filter/Filter.scss
client/src/components/MainNav/Filter/Filter.tsx
client/src/components/MainNav/Filter/SearchModal/SearchModal.scss
client/src/components/MainNav/Filter/SearchModal/SearchModal.tsx
client/src/components/MainNav/MainNav.tsx
client/src/components/MainNav/Menu/Menu.scss
client/src/components/MainNav/Profile/Profile.scss
client/src/components/ModalContainer/ModalContainer.scss
client/src/components/ModalContainer/ModalContainer.tsx
client/src/components/WriteModal/SubmitModal/SubmitModal.scss
client/src/components/WriteModal/WriteModal.scss
client/src/components/WriteModal/WriteModal.tsx
client/src/pages/Main/Main.scss
client/src/store/useAuthStore.ts
client/src/store/useModalStore.ts
client/src/styles/commons/_global-styles.scss

검색 기능 구현 (#137)

---

client/src/utils/queryString.ts

setQueryString함수 리팩터링
- related #137

setQueryString함수 숫자도 문자열화해서 return하도록 리팩터링

---

client/src/components/ModalContainer/SearchModal/SearchForm/SearchForm.scss
client/src/components/ModalContainer/SearchModal/SearchForm/SearchForm.tsx
client/src/components/ModalContainer/SearchModal/SearchForm/SearchLabel/SearchLabel.tsx
client/src/components/ModalContainer/SearchModal/SearchModal.scss
client/src/components/ModalContainer/SearchModal/SearchModal.tsx
client/src/constants/search.ts
client/src/types/post.ts

Search Modal 세부 레이아웃 구현 (#137)

---

client/src/constants/env.ts
client/src/env.d.ts

FE 환경변수들의 타입을 설정해주었습니다.
- related #150

FE 환경변수 타입 설정

---

server/src/domain/likes/likes.entity.ts
server/src/domain/likes/likes.repository.ts
server/src/domain/post/post.controller.ts
server/src/domain/post/post.module.ts
server/src/domain/post/post.repository.ts
server/src/domain/post/post.service.spec.ts
server/src/domain/post/post.service.ts
server/src/domain/post/post.subscriber.ts

좋아요, 좋아요 취소 기능을 구현한다.
- related #136 

좋아요, 좋아요 취소 기능 구현

---

package-lock.json

Root 디렉토리의 package.lock.json 삭제
- related #164 

Root 디렉토리의 package.lock.json을 삭제했습니다.

---

client/src/apis/post.ts
client/src/components/ModalContainer/SearchModal/SearchForm/SearchForm.tsx
client/src/components/ModalContainer/SearchModal/SearchModal.tsx
client/src/components/PostBar/PostBar.tsx
client/src/components/PostBar/PostLoader/PostLoader.tsx
client/src/constants/search.ts
client/src/hooks/usePostInfiniteScroll.tsx
client/src/store/useSearchStore.ts
client/src/types/post.ts
client/src/types/search.ts

- 검색 필터를 입력하고 엔터를 누르면 그 필터 정보가 PostBar에 적용되도록 수정했습니다.
- related #137

검색 필터 정보 PostBar에 적용 (#137)

---

server/src/domain/post/dto/controller-request.dto.ts
server/src/domain/post/post.service.ts

글 작성시 태그와 이미지에 대한 필터링을 수정했습니다.
- related #159 

글 작성시 태그와 이미지에 대한 필터링을 수정했습니다.

---

client/.husky/commit-msg
client/package.json
server/.husky/commit-msg
server/package.json

허스키 린트 에러를 수정하였습니다.
- related #153

husky 린트 에러 수정

---

client/src/utils/queryString.ts
client/src/utils/typeCheck.ts

검색 시 필요없는 로직은 보내지 않도록 수정하였습니다.
- related #161 

검색 시 필요없는 내용은 보내지 않게 수정하였습니다.

---

client/src/utils/queryString.ts

fix(FE): SearchQuery 타입 import 경로 버그 수정 (#144)

---

server/src/domain/post/dto/controller-request.dto.ts
server/test/post.e2e-spec.ts

["java","sort"] 꼴로 받아오던 파라미터를 java,sort 의 형태로 바꾼다
- related #168 

검색 시 태그, 사용자 파라미터의 형태를 변경

---

client/src/components/WriteModal/SubmitModal/RegisterButton/RegisterButton.tsx

usecallback 디펜던시에 tags를 추가하였습니다.
- related #123

fix(FE): 제출 usecallback 디펜던시에 tags 추가 (#170)

---

client/src/mocks/handlers/postHandler.ts
client/src/mocks/utils/postUtils.ts
client/src/types/post.ts

- 검색 필터를 로컬에서 테스트할 수 있도록 MOCK API에 추가했습니다.
- related #137 

test(FE): 검색 필터 MOCK API 추가 및 적용 (#137)

---

client/package.json

클라이언트 css, scss 프리티파이
- related #174 

클라이언트 css, scss 프리티파이 (#174)

---

server/src/domain/post-to-tag/post-to-tag.entity.ts
server/src/domain/post-to-tag/post-to-tag.repository.ts

불필요한 JoinColumn을 삭제했습니다.

---

server/src/app.module.ts
server/src/domain/auth/auth.service.ts
server/src/domain/likes/likes.controller.ts
server/src/domain/likes/likes.module.ts
server/src/domain/likes/likes.service.ts
server/src/domain/post/dto/service-response.dto.ts
server/src/domain/post/post.controller.ts
server/src/domain/post/post.entity.ts
server/src/domain/post/post.module.ts
server/src/domain/post/post.repository.ts
server/src/domain/post/post.service.spec.ts
server/src/domain/post/post.service.ts
server/test/post.e2e-spec.ts

로그인한 사용자의 경우 likesRepository에 좋아요를 누른 게시물의 번호를 가져오고, 
해당되는 게시물의 좋아요 정보를 true로 바꿔주는 방식을 통해 
사용자가 응답받는 게시물들에 좋아요 정보를 붙여 보내줍니다.
- related #136 

좋아요 기능을 구현했습니다

---

client/src/apis/auth.ts
client/src/apis/review.ts
client/src/hooks/usePostInfiniteScroll.tsx
client/src/hooks/useReviewInfiniteScroll.tsx
client/src/mocks/handlers.ts
client/src/mocks/handlers/authHandler.ts
client/src/mocks/handlers/postHandler.ts
client/src/mocks/handlers/reviewHandler.ts
client/src/mocks/mockData.ts
client/src/mocks/utils/postUtils.ts
client/src/react-query/queryKeys.ts
client/src/store/useAuthStore.ts
client/src/types/auth.ts
client/src/types/post.ts
client/src/types/review.ts

리뷰 인피니티 스크롤 훅을 개발하였습니다.
진행하며 react query 사용하는 훅 관련 리팩토링도 함께 진행였습니다.
- related #146 

리뷰 관련 훅과 리팩터링

---

server/src/domain/review/dto/controller-request.dto.ts
server/src/domain/review/dto/controller-response.dto.ts
server/src/domain/review/review.controller.ts
server/src/domain/review/review.module.ts
server/src/domain/review/review.repository.ts
server/src/domain/review/review.service.ts

인피니트 스크롤 방식의 리뷰 목록 조회 기능을 구현했습니다.
- related #176 

백엔드 리뷰 목록 조회 기능을 구현했습니다.

---

server/src/domain/auth/access-token.guard.ts
server/src/domain/auth/auth.controller.ts
server/src/domain/auth/auth.service.spec.ts
server/src/domain/auth/refresh-token.guard.ts
server/src/domain/post/post.service.spec.ts

토큰 재발급시 토큰에 id값이 들어있지 않은 오류가 있어, 값을 검사하도록 수정했습니다.
- related #192 

토큰 재발급시 토큰 내부 값을 검사하도록 수정했습니다.

---

server/src/domain/auth/auth.service.spec.ts
server/src/domain/likes/likes.service.ts
server/src/domain/post/dto/controller-request.dto.ts
server/src/domain/post/dto/service-response.dto.ts
server/src/domain/post/post.controller.ts
server/src/domain/post/post.entity.ts
server/src/domain/post/post.repository.ts
server/src/domain/post/post.service.spec.ts
server/src/domain/post/post.service.ts
server/src/domain/post/post.subscriber.ts
server/src/exception/unauthorize.exception.ts
server/src/main.ts
server/test/auth.e2e-spec.ts
server/test/post.e2e-spec.ts

게시물을 soft-delete 방식으로 삭제하고, 연관된 데이터들을 함께 삭제합ㄴ디ㅏ.
- related #187 

게시물 삭제 기능을 구현했습니다

---

client/src/apis/post.ts
client/src/components/Code/CodeLines.tsx
client/src/components/Modal/WriteModal/SubmitModal/RegisterButton/RegisterButton.tsx
client/src/types/post.ts
client/src/utils/code.ts

코드 줄줄 수 보내는 로직을 추가합니다.
- related #177 

feat(FE): 코드 줄을 보내는 로직을 추가하였습니다 (#177)

---

server/src/domain/post/post.repository.ts
server/src/domain/post/post.service.spec.ts
server/src/domain/post/post.service.ts

검색할 때 리뷰 개수로 필터링하는 기능을 구현했습니다

---

client/src/apis/auth.ts
client/src/hooks/useOAuthPopup.tsx

토큰 리프레쉬 관련 버그 수정
- related #199

fix(FE): 새로고침 시 토큰 날라가는 버그 수정 (#199)

---

client/src/apis/auth.ts

리프레쉬 요청 주소를 변경했습니다.
- related #199
- [ㅌ] 의미 있는 커밋 메시지를 작성했는가?

fix(FE): 리프레쉬 요청 주소 변경 (#199)

---

client/src/apis/interceptors/refresh.ts
client/src/hooks/useOAuthPopup.tsx
client/src/mocks/handlers/authHandler.ts
client/src/mocks/mockData.ts
client/src/types/auth.ts

refresh api를 모킹하고
expiresIn이 혹시 문자열로 취급하여 refresh가 계속 동작하는 건가 싶어 수정하였습니다.
- related #199 

feat(FE): refresh 모킹 및 expiresin 숫자로 가공 (#199)

---

server/src/app.module.ts
server/src/domain/likes/likes.controller.ts
server/src/domain/post/dto/controller-request.dto.ts
server/src/domain/post/post.controller.ts
server/src/domain/post/post.service.ts
server/src/domain/report/dto/controller-request.dto.ts
server/src/domain/report/report.controller.ts
server/src/domain/report/report.entity.ts
server/src/domain/report/report.module.ts
server/src/domain/report/report.repository.ts
server/src/domain/report/report.service.ts
server/src/domain/review/dto/controller-request.dto.ts
server/src/domain/review/review.controller.ts
server/src/domain/review/review.service.ts
server/src/exception/post-already-reported.exception.ts
server/src/exception/post-not-reported.exception.ts
server/src/exception/post-not-written.exception.ts
server/src/exception/review-not-written.exception.ts
server/src/main.ts
server/test/auth.e2e-spec.ts
server/test/post.e2e-spec.ts

- 게시물 신고 기능을 구현했습니다.
- AuthGuard를 모두 적용했습니다.
- Pipe 옵션 변경에 따라 validator 데코레이터를 수정했습니다.
- related #134 

게시물 신고 기능을 구현하고, 많은 에러를 잡았습니다.

---

client/src/App.scss
client/src/components/CommonButtons/SvgIconButton/SvgIconButton.scss
client/src/components/CommonButtons/SvgIconButton/SvgIconButton.tsx
client/src/components/Modal/SearchModal/SearchForm/SearchForm.tsx
client/src/components/PostScroll/Post/Post.scss
client/src/components/PostScroll/Post/PostFooter/LikeButton/LikeButton.tsx
client/src/components/PostScroll/Post/PostFooter/MoreButton/MoreButton.tsx
client/src/components/PostScroll/Post/PostFooter/ReportButton/ReportButton.tsx
client/src/components/PostScroll/Post/PostFooter/ReviewButton/ReviewButton.tsx
client/src/components/PostScroll/Post/PostFooter/ShareButton/ShareButton.tsx
client/src/components/ScrollLoader/ScrollLoader.scss
client/src/mocks/handlers/postHandler.ts
client/src/mocks/utils/postUtils.ts
client/src/utils/queryString.ts
client/src/utils/regExpression.ts

필터 검색 방식 변경, Post Footer의 버튼 컴포넌트 변경 (#93, #207)

---

server/nest-cli.json
server/package-lock.json
server/package.json
server/src/domain/auth/auth.controller.ts
server/src/domain/auth/auth.service.ts
server/src/domain/likes/likes.controller.ts
server/src/domain/post/dto/controller-request.dto.ts
server/src/domain/post/post.controller.ts
server/src/domain/post/post.service.spec.ts
server/src/domain/post/post.service.ts
server/src/domain/report/dto/controller-request.dto.ts
server/src/domain/report/report.controller.ts
server/src/domain/report/report.service.ts
server/src/domain/review/dto/controller-request.dto.ts
server/src/domain/review/review.controller.ts
server/src/exception/token-not-found.exception.ts
server/src/exception/token-not-permitted.exception.ts
server/src/exception/unauthorize.exception.ts
server/src/exception/user-not-same.exception.ts
server/src/main.ts

Swagger를 사용해 API 문서를 만들었습니다
- related #212 

Swagger를 사용해 API 문서를 만들었습니다

---

client/.stylelintrc.json
client/package-lock.json
client/package.json

스타일 린트 설정을 추가하였습니다.
[recess 정렬방식](https://github.com/stormwarning/stylelint-config-recess-order)을 사용하기로 결정 후 적용하였습니다.
- related #226 

FE stylelint 설정 추가 

---

server/package-lock.json
server/package.json
server/src/domain/auth/auth.controller.ts
server/src/domain/auth/auth.module.ts
server/src/domain/auth/ncp-object-storage.ts

- 이미지 업로드 Presigned URL을 생성하는 기능을 구현했습니다.
- jpeg 파일만 업로드할 수 있으며, 파일의 최대 용량은 10MB로 제한했습니다.
- related #232 

이미지 업로드 Presigned URL을 생성하는 기능을 구현했습니다. (#232)

---

client/src/apis/post.ts

병합 간 스토어 분리가 적용되지 않은 것 같아서 수정했습니다!
- fix #238 

fix(FE): 변경된 전역 스토어 상태 적용 (#238)

---

client/src/components/Modal/WriteModal/SubmitModal/RegisterButton/RegisterButton.tsx

- 샘플 데이터 제거하고 상태 데이터를 사용하도록 변경
- fix #238 

fix(FE): 샘플 데이터를 이용하던 로직에서 생성된 이미지를 이용하도록 변경 (#238)

---

client/src/apis/post.ts

fix(FE): 전송 환경 초기화 (#238)

---

client/src/apis/post.ts

fix(FE): FormData 올바른 순서로 변경 (#238)

---

client/src/components/Modal/WriteModal/SubmitModal/RegisterButton/RegisterButton.tsx

- 확인해보니 pipe 함수의 결과로 Promise 객체가 전달되는 이슈가 있었습니다.
- fix #238 

fix(FE): pipe 함수로 Promise 객체가 넘어가는 버그 수정 (#238)

---

server/.gitignore
server/src/domain/image/image.entity.ts
server/src/domain/post/post.entity.ts
server/src/domain/report/report.entity.ts
server/src/domain/tag/tag.entity.ts
server/src/domain/user/user.entity.ts

- TypeORM의 varchar 컬럼들의 길이를 지정했습니다.
- related #245 

TypeORM varchar 길이를 지정했습니다. (#245)

---

client/src/apis/post.ts
client/src/components/PostScroll/Post/PostFooter/LikeButton/LikeButton.tsx
client/src/hooks/usePostLike.ts
client/src/mocks/handlers/postHandler.ts
client/src/types/post.ts

좋아요 토글 기능을 추가하였습니다.
- related #215

좋아요 토글 기능 추가 (#215)

---

client/src/App.scss
client/src/components/main/Modal/ReviewModal/ReviewModal.scss
client/src/components/main/Modal/SearchModal/SearchForm/SearchLabel/SearchLabel.scss
client/src/components/main/Modal/SearchModal/SearchForm/SearchLabel/SearchLabel.tsx
client/src/components/main/Modal/SearchModal/SearchModal.scss
client/src/components/main/Modal/WriteModal/WriteModal.scss
client/src/components/main/Modal/WriteModal/WriteModal.tsx
client/src/components/main/Modal/WriteModal/WritingForm/LanguageSelector/LanguageSelector.scss
client/src/components/main/Modal/WriteModal/WritingForm/LanguageSelector/LanguageSelector.tsx
client/src/components/main/Modal/WriteModal/WritingForm/SubmitButton/SubmitButton.tsx
client/src/components/main/Modal/WriteModal/WritingForm/WritingForm.tsx
client/src/pages/Main/Main.scss
client/src/pages/Main/Main.tsx

- import 미반영 등 스타일이 적용되지 않던 컴포넌트를 마저 정리했습니다.
- related #220 

refactor(FE): Style 변경 미반영 컴포넌트 반영 (#220)

---

server/src/domain/auth/auth.controller.ts
server/src/domain/auth/ncp-object-storage.ts
server/src/domain/post/post.controller.ts
server/src/domain/post/post.service.spec.ts
server/src/domain/post/post.service.ts
server/src/domain/report/report.controller.ts
server/src/domain/report/report.service.ts
server/src/domain/review/review.controller.ts
server/src/domain/review/review.service.ts
server/src/exception/post-not-written.exception.ts
server/src/exception/review-not-written.exception.ts

- 서비스 계층에서 커스텀 에러를 던지던 부분을 삭제했습니다.
- related #248 

서비스 레이어에서 에러를 제거했습니다. (#248)

---

.github/workflows/client-integration.yml
.github/workflows/dev-client-deploy.yml
.github/workflows/dev-server-deploy.yml
.github/workflows/main-client-deploy.yml
.github/workflows/main-server-deploy.yml
.github/workflows/server-integration.yml
client/package.json
server/package.json

ci(BE): 실서버 자동배포 설정 (#258)

---

.github/workflows/dev-client-deploy.yml

ci(DO): 환경변수 이름 수정 (#258)

---

.github/workflows/main-server-deploy.yml

도커 이미지 태그를 변경했습니다. (#258)

---

server/src/domain/auth/auth.controller.ts

refresh Token에 secure 설정을 했습니다.

쿠키 secure 설정

---

server/src/domain/auth/auth.controller.ts

- 쿠키에 secure설정이 되어 있지 않아서 실서버에서 오류가 발생
- related #258

feat(BE): 쿠키 secure 설정 (#258)

---

server/src/domain/auth/ncp-object-storage.ts

NCP 오브젝트 스토리지 버킷명 환경변수화

---

.github/workflows/main-server-deploy.yml

도커 이미지에 latest 태그를 추가했습니다. (#258)

---

.github/workflows/main-server-deploy.yml
server/src/domain/auth/auth.controller.ts

v0.1.0 배포 버그 수정 - 환경변수 적용, 도커 이미지 태그 수정

---

client/src/apis/post.ts
client/src/utils/regExpression.ts

코드를 html 형식으로 prevent하지 않고 서버로 보냅니다.
- related #272

코드를 html 형식으로 prevent하지 않고 서버로 보냅니다.

---

scheduler-server/.eslintrc.js
scheduler-server/.gitignore
scheduler-server/.prettierrc
scheduler-server/README.md
scheduler-server/nest-cli.json
scheduler-server/package-lock.json
scheduler-server/package.json
scheduler-server/src/app.module.ts
scheduler-server/src/exception/tag-count-invalid.exception.ts
scheduler-server/src/exception/tag-duplicated.exception.ts
scheduler-server/src/exception/tag-name-invalid.exception.ts
scheduler-server/src/main.ts
scheduler-server/src/ranking/dto/controller-request.dto.ts
scheduler-server/src/ranking/ranking.controller.ts
scheduler-server/src/ranking/ranking.module.ts
scheduler-server/src/ranking/ranking.service.ts
scheduler-server/test/jest-e2e.json
scheduler-server/test/ranking.e2e-spec.ts
scheduler-server/tsconfig.build.json
scheduler-server/tsconfig.json

사용자들이 검색한 태그를 저장하고 일정한 주기에 따라 태그들의 인기 순위를 갱신합니다.
사용자들이 요청을 보내면 저장한 순위에 따라 태그들의 랭킹을 반환합니다.
(fix #일이삼) 
- related #275
- related #278 

실시간 인기 태그를 보여주는 기능을 구현했습니다

---

.github/workflows/dev-scheduler-server-deploy.yml
.github/workflows/main-scheduler-server-deploy.yml
.github/workflows/scheduler-server-integration.yml
scheduler-server/Dockerfile

scheduler server에 ci/cd를 적용했습니다
- related #283 

scheduler server에 ci/cd를 적용했습니다

---

.github/workflows/dev-scheduler-server-deploy.yml

datach -> detach로 오타를 수정했습니다
- related #283

설정 파일 오타 수정

---

client/src/apis/search.ts
client/src/mocks/handlers/searchHandler.ts

- fix #303 
- related #280 
(fix #일이삼)

최근 검색어 명세 일치 오류 수정

---

client/src/styles/_animation.scss

tranform -> transform
- related #305 

transform spelled

---

server/src/domain/user/user.controller.ts

- 검색 기록이 없을 때 빈 배열을 반환하도록 수정했습니다.
- related #303 

fix(BE): 검색 기록이 API 명세와 맞지 않는 오류 수정 (#303)

---

server/src/domain/post/dto/controller-request.dto.ts
server/src/domain/post/post.controller.ts
server/src/domain/search/dto/controller-response.dto.ts
server/src/domain/search/search-history.mongo.repository.ts
server/src/domain/user/user.controller.ts
server/src/domain/user/user.service.ts
server/src/exception/search-history-not-found.exception.ts

- 최근 검색어 삭제 기능을 구현했습니다.
- 최근 검색어를 가져오는 기능을 최신 순으로 5개를 가져오도록 변경했습니다.
- related #311 

최근 검색어 삭제 기능을 구현했습니다.

---

client/src/apis/post.ts
client/src/components/main/MainNav/NavContent/ProfileContent/ProfileContent.tsx
client/src/components/main/TagRanking/TagRankingItem/TagRankingItem.tsx
client/src/hooks/useLabel.ts
client/src/hooks/usePostInfiniteScroll.ts
client/src/mocks/datasource/mockDataSource.ts
client/src/mocks/handlers/postHandler.ts
client/src/store/useSearchStore.ts
client/src/types/search.ts

- 프로필 메뉴에서 내 포스트를 누르면 내가 작성한 포스트만 볼 수 있다.
- 관련 MOCK API 구현
- related #299

feat(FE): 내 포스트 보기 API 적용 및 인피니티 스크롤 연결 (#299)

---

server/src/domain/post/post.service.ts

깃허브에서 충돌을 해결하는 과정에서 } 하나가 누락되서 발생한 이슈입니다.
-related #317 

fix(BE): 오탈자로 인한 오류 해결 (#317)

---

server/src/app.module.ts
server/src/domain/bookmark/bookmark.controller.ts
server/src/domain/bookmark/bookmark.entity.ts
server/src/domain/bookmark/bookmark.module.ts
server/src/domain/bookmark/bookmark.repository.ts
server/src/domain/bookmark/bookmark.service.ts
server/src/domain/bookmark/dto/controller-request.dto.ts
server/src/domain/user/user.controller.ts
server/src/exception/bookmark-not-found.exception.ts
server/src/exception/post-already-bookmarked.exception.ts

- 북마크 목록 GET /api/bookmarks?lastId=
- 북마크 추가 POST /api/bookmarks  |  body에 postId
- 북마크 삭제 DELETE /api/bookmarks?postId=
- related #293 

북마크 목록, 추가, 삭제 기능을 구현했습니다.

---

server/src/domain/bookmark/bookmark.service.ts

- 북마크 목록에서 isLast의 조건 중 이상한 부분을 수정했습니다.
- related #293 

북마크 목록 isLast 로직 수정

---

server/src/domain/bookmark/bookmark.service.ts
server/src/domain/post/dto/service-response.dto.ts
server/src/domain/post/post.controller.ts
server/src/domain/post/post.module.ts

- 글 목록 정보에 북마크 여부를 추가했습니다.
- 구조에 이슈가 있어 북마크된 글 목록에서 isLiked가 false로 나타납니다. 시간이 걸리는 작업같아서 일단 처리하지 않았습니다.
- related #293 

글 목록 정보에 북마크 여부를 추가했습니다.

---

client/src/ReactRouter.tsx
client/src/apis/post.ts
client/src/components/main/MainNav/NavHeader/NavHeader.tsx
client/src/components/main/PostScroll/Post/PostFooter/LeftBlockItems/ShareButton.tsx
client/src/mocks/handlers/postHandler.ts
client/src/pages/Post/Post.scss
client/src/pages/Post/Post.tsx

게시글 공유 기능을 추가하고 각각의 포스트별 라우터를 만들었습니다.
(fix #일이삼)
- related #313

게시글 공유 기능 추가 

---

client/src/App.scss
client/src/components/main/CodeEditor/CodeEditor.scss
client/src/components/main/CodeEditor/CodeEditor.tsx
client/src/components/main/MainNav/NavHeader/NavHeader.tsx
client/src/hooks/useEditorScroll.ts
client/src/styles/_mixin.scss

에디터 폰트 적용 및 스크롤 기능, 글쓰기 모달이 시작될 때 focusing되도록 설정
- related #224 

글쓰기 모달 관련 디테일한 작업

---

server/src/domain/post/post.controller.ts

검색조건에 아무 값도 넣지 않은 경우, 스케쥴러 서버에서 발생하는 에러를 처리했습니다.
- related #330 

스케쥴러 서버에 빈 배열을 요청보낼 때 예외를 처리했습니다.

---

server/src/domain/post/post.controller.ts

API 명세에 맞춰 단건 조회 시 post를 감싸서 보내도록 변경했습니다.
- related #330 

API 명세에 맞춰 단건 조회 시 post를 감싸서 보내도록 변경했습니다.

---

client/src/components/main/MainNav/NavContent/SearchContent/SearchContent.scss
client/src/components/main/MainNav/NavContent/SearchContent/SearchContentHeader/DetailSearchForm/DetailSearchForm.scss
client/src/components/main/MainNav/NavContent/SearchContent/SearchContentHeader/DetailSearchForm/DetailSearchForm.tsx
client/src/components/main/MainNav/NavContent/SearchContent/SearchContentHeader/SearchContentHeader.scss
client/src/components/main/MainNav/NavContent/SearchContent/SearchContentHeader/SearchContentHeader.tsx
client/src/constants/search.ts
client/src/hooks/useLabel.ts
client/src/mocks/utils/mockUtils.ts
client/src/store/useLabelStore.ts
client/src/styles/_mixin.scss

https://user-images.githubusercontent.com/63703962/205975375-07f1d0e8-30a7-476c-82ad-d7424f0c1316.mov
- related #289 

FE 상세 검색 (좋아요 수, 리뷰 수) 구현 (#289)

---

client/src/hooks/useRefreshInterceptor.ts

첫번째 refresh된 요청에 헤더 안 붙는 에러 수정 (#339)
- related #339 

fix(FE): 첫번째 refresh된 요청에 헤더 안 붙는 에러 수정 (#339)

---

server/src/domain/bookmark/bookmark.repository.ts
server/src/domain/bookmark/bookmark.service.ts

- 북마크 게시물 작성자가 자신으로 설정되는 오류를 수정했습니다.
- related #340 

북마크 게시물 작성자가 자신으로 설정되는 오류를 수정했습니다.

---

client/src/hooks/useRefreshInterceptor.ts

새로 고침 시 refresh가 발생하지 않는 에러를 해결했습니다.
- related #339 

새로고침 시 refresh가 되지 않는 오류 (#339)

---

server/src/domain/post/post.controller.ts
server/src/domain/search/search-history.mongo.repository.ts
server/src/domain/user/user.service.ts

- 유저 사용성 향상을 위해 검색시 최근 검색어 저장 기능을 동기화했습니다.
- related #347 

fix(BE): 검색시 최근 검색어 저장 기능 동기화 (#347)

---

client/src/hooks/useBookmark.ts
client/src/hooks/useLabel.ts
client/src/hooks/usePostLike.ts
client/src/pages/Post/Post.scss
client/src/pages/Post/Post.tsx

메인화면 previous data undefined인 에러 수정
개별 포스트 화면에서 좋아요나 스크랩 클릭시 깜빡이는 에러 수정
검색 안 되는 에러 수정
스크롤 추가
- related #349 
- related #359

공유하기 부분 에러 수정

---

client/src/App.scss
client/src/components/main/CodeEditor/CodeEditor.tsx
client/src/components/main/Modal/ReviewModal/ReviewModal.tsx
client/src/hooks/useCodeEditor.ts

인기 태그 레이아웃 수정 및 줄 수 탭 기능 추가 
- related #354 
- related #371 
- related #372 

인기 태그 레이아웃 수정 및 줄 수 탭 기능 추가 

---

server/src/domain/post/post.service.spec.ts

- CI 개선을 위해 동작하지 않는 테스트 코드를 비활성화했습니다.
- related #382 

변경된 DTO 사양이 반영되지 않은 테스트 코드를 비활성화했습니다.

---

.github/workflows/integration-api-server.yml
.github/workflows/integration-client.yml
.github/workflows/integration-scheduler-server.yml
.github/workflows/reusable-deployment-client.yml
.github/workflows/reusable-deployment-server.yml
.github/workflows/reusable-integration.yml

- 기존 reusable workflow의 name에 큰따옴표가 없어 에러가 나던 것을 수정했습니다.
- CI는 프론트엔드와 백엔드의 환경이 거의 동일하여 같은 명령어를 사용하기에 reusable workflow로 공통 로직을 분리했습니다.
- 전체 CI와 프론트엔드 CD에 깃허브 액션의 캐시 액션을 적용했습니다.
- 개인 레포지토리에서 같은 코드로 테스트했을 때, 캐시를 사용하면 CI 시간이 기존보다 절반이나 절약되는 것을 확인했습니다.
- related #382 

CI에 reusable workflow를 적용하고, Github actions 캐싱을 적용했습니다.

---

client/src/components/main/Modal/WriteModal/SubmitModal/RegisterButton/RegisterButton.tsx
client/src/components/main/Modal/WriteModal/WritingForm/LanguageSelector/LanguageSelector.tsx
client/src/components/main/Modal/WriteModal/WritingForm/WritingForm.tsx
client/src/hooks/useCodeEditor.ts
client/src/hooks/useSnapshotCodeBlock.ts
client/src/store/useCodeEditorStore.ts
client/src/utils/async.ts

- 스냅샷 찍히지 않은 부분 알아서 남는 줄 스냅샷 되는 기능 추가
- 언어 바뀔 때 자동 스냅샷 수정 기능 추가
- related #350 

스냅샷 관련 기능 추가 

---

.github/workflows/reusable-deployment-server.yml

- 간단한 오타를 수정했습니다.
- related #398 

fix(DO): 서버 reusable workflow 파일 내 오타 수정 (#398)

---

client/src/components/main/MainNav/NavMenus/NewPostMenu/NewPostMenu.tsx
client/src/hooks/useRefreshInterceptor.ts

로그인 안 될 때 새 포스트를 누르면 로그인으로 유도합니다.
response에 401이 발생하면 사용자 정보가 있고 없고를 분기해서 리프레시하거나 로그인을 유도합니다.
- related #393 

권한 없음을 핸들링 했습니다.

---

client/src/components/main/Modal/ReviewModal/ReviewScroll/Review/Review.scss
client/src/components/main/PostScroll/Post/PostBody/PostBody.scss
client/src/components/main/PostScroll/Post/PostBody/PostBody.tsx
client/src/components/main/PostScroll/Post/PostFooter/RightBlockItems/PostMoreModal/PostMoreModal.tsx
client/src/constants/code.ts
client/src/mocks/datasource/mockDataSource.ts

포스트 본문 표시 변경 및 개행을 포함하도록 변경 (#379)

---

client/src/components/commons/Modal/core/ModalOverlay/ModalOverlay.scss
client/src/components/main/Modal/ModalWrapper/ModalWrapper.scss
client/src/styles/_mixin.scss

- 중간 색깔로 통일
- blur 효과 추가
- 믹스인 분리
- related #381 

design(FE): 모달 배경 레이아웃 통일 및 믹스인 분리 (#381)

---

.github/workflows/reusable-deployment-client.yml

hashFiles 문법 오류로 작은따옴표로 변경했습니다.

---

client/src/pages/Main/Main.scss

- 모달창이 떠도 더이상 배경 레이아웃이 밀리지 않도록 수정했습니다.
- fix #396 

design(FE): 불필요한 gap 속성으로 인한 밀림 수정 (#396)

---

client/src/components/main/MainNav/NavContent/SearchContent/SearchContentHeader/DetailSearchForm/DetailSearchForm.tsx
client/src/components/main/Modal/WriteModal/SubmitModal/TagInput/TagInput.scss
client/src/components/main/Modal/WriteModal/SubmitModal/TagInput/TagInput.tsx
client/src/constants/label.ts
client/src/constants/tag.ts
client/src/types/search.ts
client/src/utils/label.ts
client/src/utils/regExpression.ts

태그 관련 예외처리 및 레이아웃 서치라벨 이용
- related #401 

태그 관련 예외처리 및 레이아웃 서치라벨 이용 관련 수정

---

.github/workflows/deployment-dev-client.yml
.github/workflows/deployment-main-client.yml

- 클라이언트 secrets에 VITE 문자열이 누락된 오류를 수정했습니다.
- related #398 

클라이언트 secrets에 VITE 누락 수정

---

server/src/domain/bookmark/bookmark.repository.ts
server/src/domain/post/post.repository.ts
server/src/domain/user/user.controller.ts
server/src/domain/user/user.module.ts

- 북마크 목록에서 인피니트 스크롤이 제대로 동작하지 않는 오류를 수정했습니다.
- 삭제된 글이 북마크, 내 글 목록에서 보이는 오류를 수정했습니다.
- related #380 

fix(BE): 삭제된 글이 북마크, 내 글 목록에 보이는 오류 수정 및 북마크 lastId 적용 (#380)

---

server/src/domain/user/user.module.ts

- providers가 누락되어 자동 주입이 되지 않아 발생하는 오류를 수정했습니다.
- releated #380 

providers가 누락되어 수정했습니다.

---

client/src/components/main/MainNav/NavContent/SearchContent/SearchContentBody/SearchContentRecommend.tsx
client/src/components/main/PostScroll/NoPost/NoPost.scss
client/src/components/main/PostScroll/NoPost/NoPost.tsx
client/src/components/main/PostScroll/PostScroll.tsx

조회된 글이 없을 때 진행사항 보여주기 및 다른 검색어 유도 
- related #414

조회된 글이 없을 때 진행사항 보여주기 및 다른 검색어 유도 

---

client/src/components/main/PostScroll/Post/PostImageSlider/PostImageSlider.scss
client/src/components/main/PostScroll/Post/PostImageSlider/PostImageSlider.tsx
client/src/components/main/PostScroll/Post/PostImageSlider/SlideButton/SlideButton.scss
client/src/components/main/PostScroll/Post/PostImageSlider/SlideButton/SlideButton.tsx
client/src/constants/style.ts
client/src/mocks/datasource/mockDataSource.ts
client/src/utils/style.ts

이미지 슬라이더 추가
이미지 슬라이딩을 나타내는 점 추가
https://user-images.githubusercontent.com/83356118/207259599-4f87e99e-ce86-45e7-a391-5a1e975f681b.mov
(fix #일이삼)

이미지 슬라이더 추가

---

.github/workflows/deployment-main.yml

- 띄어쓰기를 수정했습니다.
- related #382 

yaml 문법을 수정했습니다.

---

.github/workflows/deployment-dev.yml
.github/workflows/deployment-main.yml
.github/workflows/integration.yml

- paths filter가 main과 비교하는 오류를 수정했습니다.
- related #382 

paths filter 비교 대상이 이상한 오류 수정

---

client/src/components/main/PostScroll/Post/PostImageSlider/PostImageSlider.scss
client/src/components/main/PostScroll/Post/PostImageSlider/PostImageSlider.tsx
client/src/utils/style.ts

슬라이더 dots 투명도 설정 및 모바일 슬라이딩 기능 구현
- related #93 

슬라이더 dots 투명도 설정 및 모바일 슬라이딩 기능 구현

---

server/src/domain/post/dto/controller-response.dto.ts
server/src/domain/post/post.controller.ts
server/src/domain/post/post.service.ts

앞선 수정사항이 제대로 먹지 않았습니다.
확인해보니 authorId가 아닌, userId를 받아오고 있어 변수명을 수정해줬습니다.
- related #432 

fix(BE): 검색이 이상하게 되는 경우들을 수정하였습니다 -2차

---

client/src/components/main/PostScroll/Post/PostTitle/PostTitle.scss
client/src/components/main/PostScroll/PostScrollSkeleton/PostScrollSkeleton.scss
client/src/components/main/PostScroll/PostScrollSkeleton/PostScrollSkeleton.tsx
client/src/components/main/TagRanking/TagRankingSkeletonItem/TagRankingSkeletonItem.scss
client/src/hooks/usePostInfiniteScroll.ts
client/src/mocks/handlers/postHandler.ts
client/src/pages/Main/Main.tsx
client/src/pages/Post/Post.tsx
client/src/styles/_animation.scss
client/src/styles/_mixin.scss
client/src/styles/_theme.scss

- 초기 버전
https://user-images.githubusercontent.com/63703962/207800082-0d615498-c1b9-4810-9232-698e96977756.mov
- 애니메이션 추가
https://user-images.githubusercontent.com/63703962/207811411-bb2968e6-311b-447c-b8e9-52c0fb18659c.mov
- 포스트 첫 로딩 시 스켈레톤 UI를 표시하도록 구현
- Main페이지, 공유된 페이지 적용 확인
- 로컬에서 확인하기 쉽도록 첫 페이지 로딩 지연시간 증가
- 디자인 조언 적용 및 애니메이션 추가
- 이미지 스켈레톤만 너무 튀는거 같아서 의견을 구하고 있어요.
1. 그냥 유지
2. 회색으로 통일
3. 투명도 조절
- related #291 

feat(FE): 포스트 목록 스켈레톤 UI 적용 (#291)

---

client/src/components/main/Modal/WriteModal/SubmitModal/ContentArea/ContentArea.scss
client/src/components/main/Modal/WriteModal/SubmitModal/ContentArea/ContentArea.tsx
client/src/components/main/Modal/WriteModal/SubmitModal/RegisterButton/RegisterButton.scss
client/src/components/main/Modal/WriteModal/SubmitModal/SubmitModal.scss
client/src/components/main/Modal/WriteModal/SubmitModal/SubmitModal.tsx
client/src/components/main/Modal/WriteModal/SubmitModal/TagInput/TagInput.scss
client/src/components/main/Modal/WriteModal/SubmitModal/TagInput/TagInput.tsx
client/src/components/main/Modal/WriteModal/SubmitModal/TitleInput/TitleInput.scss
client/src/components/main/Modal/WriteModal/SubmitModal/TitleInput/TitleInput.tsx

Submit Modal 레이아웃 수정
- related #422

Submit Modal 레이아웃 수정 (#422)

---

client/src/components/main/Modal/WriteModal/SubmitModal/TitleInput/TitleInput.scss

타이틀 input 폰트 사이즈 변경
- related #422

타이틀 input 폰트 사이즈 변경 (#422)

---

scheduler-server/src/ranking/ranking.service.ts
server/package.json
server/src/domain/report/report.service.spec.ts
server/src/domain/review/review.service.spec.ts

- 리뷰와 신고 서비스의 단위 테스트를 작성했습니다.
- related #421 

리뷰와 신고 서비스의 단위 테스트를 작성했습니다.
