boostcampwm-2022/web06-weview

client/src/components/Profile/UserProfile/UserProfile.tsx
client/src/mocks/handlers.ts
client/src/mocks/handlers/authHandler.ts
client/src/utils/localStorage.ts

- 디자인 생각 없이 로그인 된 상태의 프로필 컴포넌트 클릭 시 로그아웃 로직이 작동되도록 구현함
- msw handler를 카테고리별로 분리할 수 있도록 리팩토링
- closed #19 

FE 로그아웃 API 적용 및 Mock API 설정 (#19)

---

client/cypress.config.ts
client/cypress/e2e/login.cy.ts
client/cypress/e2e/spec.cy.ts
client/package-lock.json
client/package.json
client/src/components/Profile/NotLoggedInProfile/NotLoggedInProfile.tsx

cypress 환경에서 vite 환경 변수를 사용하기 위해 cypress-vite를 설치하여 모듈을 전처리하였습니다.
- 로그인 버튼을 누르면 깃헙 화면이 보인다.
- 로그인 성공하면 프로필 사진이 보이고 로그아웃 성공하면 로그인 버튼이 보인다. 
라고 전제하고 테스트를 작성하였습니다.
- related #53 

로그인 하고 로그아웃 하는 시나리오에 맞추어 Cypress 테스트를 작성했습니다.

---

client/src/ReactRouter.tsx
client/src/apis/post.ts
client/src/components/PostBar/Post/Post.tsx
client/src/components/PostBar/PostBar.scss
client/src/components/PostBar/PostBar.tsx
client/src/hooks/useIntersect.tsx
client/src/hooks/usePostInfiniteScroll.tsx
client/src/mocks/handlers.ts
client/src/mocks/handlers/postHandler.ts
client/src/mocks/mockData.ts
client/src/pages/Main.tsx
client/src/types/post.ts

- 스크롤 바닥에 위치하면 다음 페이지가 5개씩(지정 가능) 로딩되도록 구현했습니다.
- 인피니티스크롤과 바닥을 감지하는 기능들을 커스텀 훅으로 분리했습니다.
- related #60

기본적인 인피니티 스크롤 로딩 구현 (#60)

---

client/.husky/pre-push
client/package.json
server/.husky/pre-push
server/package.json

dev main 브랜치로 push 하는 실수를 방지하기 위해 dev main 브랜치에 push 방지용 pre push 훅을 설정해놓았습니다.
해당 이미지는 test를 위해 브랜치를 현재 브랜치로 바꾸어 테스트해놓았고 현재 설정은 dev 브랜치와 main 브랜치에 적용돼있습니다.
- related #79

dev main 브랜치 push 방지용 pre-push 훅 설정 

---

client/src/components/WriteModal/SnapShotNav/SnapShotNav.scss
client/src/components/WriteModal/SubmitModal/RegisterButton/RegisterButton.tsx
client/src/components/WriteModal/WriteModal.scss
client/src/components/WriteModal/WritingForm/CodeEditor/CodeEditor.scss
client/src/components/WriteModal/WritingForm/CodeEditor/CodeEditor.tsx
client/src/components/WriteModal/WritingForm/CodeEditor/CodeTheme.scss
client/src/components/WriteModal/WritingForm/LanguageSelector/LanguageSelector.tsx
client/src/components/WriteModal/WritingForm/WritingForm.scss
client/src/constants/_library.scss
client/src/constants/options.ts
client/src/store/useWritingStore.ts
client/src/utils/regExpression.ts

언어 선택에 맞추어 코드가 하이라이팅 될 수 있도록 수정하고 github-dark 테마를 적용하였습니다.
또 code는 기본적으로 다양한 script들을 사용할 가능성이 있다고 생각하여 react가 react dom을 만들 떄 기본적으로 escaping을 하지만 response를 복사해서 다른 웹에서 사용하는 것등을 고려해서 escaping을 추가하였습니다.
- related #126

언어 선택에 따른 코드 하이라이팅 기능 및 xss 방지 기능 추가 

---

server/src/domain/post/dto/controller-request.dto.ts
server/src/domain/post/dto/service-request.dto.ts
server/src/domain/post/post.controller.ts
server/src/domain/post/post.repository.ts
server/src/domain/post/post.service.spec.ts
server/src/domain/post/post.service.ts
server/test/post.e2e-spec.ts

파라미터 이름을 변경해주고, lastId에 기본값을 넣습니다
변경된 파라미터
- writtenAnswer -> reviews
- scores -> likes
- search -> detail
- related #152 

API 명세 변경에 따른 게시물 목록 조회 파라미터 수정

---

client/src/apis/review.ts
client/src/components/CommonButtons/CommonButtons.scss
client/src/components/MainNav/Profile/NotLoggedInProfile/NotLoggedInProfile.tsx
client/src/components/Modal/ReviewModal/ReviewContainer/ReviewContainer.tsx
client/src/components/Modal/ReviewModal/ReviewContainer/ReviewForm/NotLoggedInReviewForm.tsx
client/src/components/Modal/ReviewModal/ReviewContainer/ReviewForm/ReviewForm.scss
client/src/components/Modal/ReviewModal/ReviewContainer/ReviewForm/ReviewForm.tsx
client/src/components/Modal/ReviewModal/ReviewModal.scss
client/src/hooks/useOAuthPopup.tsx
client/src/types/review.ts

- 로그인이 되지 않았을 시 로그인 요청 컴포넌트로 표시
- 로그인 되었을 시 맨 위에 프로필을 보여줌
- 텍스트 입력은 일단 기본 텍스트 입력만 지원, 세로로 크기 2배까지 조절 가능
- 제출 버튼 클릭 시 API 호출 (TODO: API 호출이 잘 되는걸 확인하고 progress를 표시한다거나, 전송 완료 시 content 부분을 초기화하는 부분 구현 예정)
- related #147 

리뷰 작성 컴포넌트 구현 및 리뷰 Post 요청 API 적용 (#147)

---

client/src/components/PostScroll/PostScroll.tsx

- PostScroll에서 바닥에 도착하면 더이상 로딩을 위한 Spinner가 보이지 않음 (이전 기능에서 추가했지만 PostScroll에 적용하지 않은 오류 수정)
- related #147 

fix(FE): PostScroll 마지막 페이지 확인 후 Spinner 표시하는 기능 누락 수정 (#147)

---

server/src/domain/likes/likes.controller.ts
server/src/domain/post/post.controller.ts
server/src/domain/report/report.controller.ts
server/src/domain/review/review.controller.ts
server/src/main.ts

토큰의 이름을 refresh-token에서 refreshToken으로 바꾸던 중, 누락된 부분들이 있어 Swagger가 인식하지 못하는 문제를 해결했습니다.
- related #228 

fix(BE): Swagger에서 refreshToken이 적용되지 않는 이슈 해결 (#228)

---

scheduler-server/package.json
scheduler-server/src/main.ts
scheduler-server/src/ranking/dto/controller-request.dto.ts
scheduler-server/src/ranking/ranking.controller.ts

스케쥴러 서버에 Swagger를 적용하고, 엔드포인트를 api/로 맞춰줬습니다.
- docker-compose 설정 
```
swagger:
image: swaggerapi/swagger-ui
environment:
- URLS=
[
{'localhost/api/-json',name:'Post'},
{'localhost:8080/-json', name:'Ranking'},
]
```
- related #286 
- 

스케쥴러 서버에 Swagger를 적용했습니다

---

scheduler-server/src/ranking/ranking.controller.ts

랭킹 서버에서 ranking이라는 url이 하나 더 들어가는 게 Restful하지 않다 생각해,
기존 서버url/ranking/tags로 접근하던 방식에서 서버url/tags로 접근할 수 있게 url을 변경했습니다.
docker-compose 설정 변경
```
swagger:
image: swaggerapi/swagger-ui
environment:
- URLS=
[
{'localhost/api/-json',name:'Post'},
{'localhost/api/ranking/-json', name:'Ranking'},
]
```
nGinx 설정 변경
```
location /api/ranking/ {
proxy_pass http://localhost:8080/;
}
```
- related #286 

Ranking 서버의 RankingController url를 변경했습니다

---

client/src/components/commons/SearchLabel/SearchLabel.scss
client/src/components/main/PostScroll/Post/PostTitle/AuthorProfile/AuthorProfile.tsx
client/src/components/main/PostScroll/Post/PostTitle/CodeInfo/CodeInfo.tsx
client/src/constants/defaultObject.ts
client/src/constants/search.ts
client/src/hooks/useLabel.ts
client/src/mocks/handlers/postHandler.ts
client/src/mocks/utils/postUtils.ts
client/src/store/useSearchStore.ts
client/src/types/post.ts
client/src/types/react-query.ts
client/src/types/review.ts
client/src/types/search.ts
client/src/utils/queryString.ts

- 검색 및 Post 요청 등 명세 변경에 따른 타입 변경 및 적용
- MOCK API 적용
- 검색 details 여러개를 쉼표로 구분해서 전송
- 로컬에서 MOCK API로 실행되는 부분은 확인했습니다.
- related #289 

API 명세 변경에 따른 타입 변경 및 불필요한 코드 제거 (#289)

---

server/src/app.module.ts
server/src/domain/post/post.repository.ts
server/src/domain/user/dto/controller-request.dto.ts
server/src/domain/user/user.controller.ts
server/src/domain/user/user.module.ts
server/src/domain/user/user.service.spec.ts
server/src/domain/user/user.service.ts

존재하는 사용자의 게시물만 조회가 가능합니다.
무한 스크롤 방식을 사용해 게시물의 조회가 일어납니다
- related #299 

특정 사용자의 게시물을 조회하는 기능을 구현했습니다

---

client/src/apis/search.ts
client/src/components/main/MainNav/NavContent/SearchContent/SearchHistoryView/SearchHistoryView.tsx
client/src/constants/search.ts
client/src/mocks/datasource/mockDataSource.ts
client/src/mocks/handlers/postHandler.ts
client/src/mocks/handlers/searchHandler.ts
client/src/types/search.ts

- 검색 최대 개수 제한 (상수로 관리)
- 기록 제거 기능 구현
- 관련 MOCK API수정
- related #280 

feat(FE): 최근 검색 기록 최대 5개만 가져오기, 기록 제거 버튼 기능 구현 (#280)

---

server/src/domain/post/post.repository.ts
server/src/domain/post/post.service.ts

각각의 검색어에 대해 AND 연산이 일어납니다.
상세 검색 시 필터링할 수 있는 속성은 제목, 내용, 작성자의 이름입니다.
각각의 검색어는 제목, 내용에 포함되는지, 동일한 작성자의 이름이 있는지 검색합니다.
각각의 검색어는 AND 연산이 일어나, 조건이 많아질수록 세세한 검색이 가능하도록 합니다.
각각의 조건을 만족하는 게시물들을 구한 뒤, 교집합을 사용해 상세 검색 조건을 다 만족하는 게시물만을 검색합니다.
- related #314 

fix(BE): 상세 검색시 각 검색어가 AND 연산이 일어나도록 수정 (#314)

---

server/src/domain/post/post.controller.ts
server/src/domain/post/post.repository.ts
server/src/domain/post/post.service.spec.ts
server/src/domain/post/post.service.ts
server/src/domain/user/user.controller.ts

게시물을 단건으로 조회합니다.
- related #317 

게시물 단건 조회 기능을 구현했습니다.

---

server/src/domain/post/dto/service-response.dto.ts
server/src/domain/post/post.repository.ts
server/src/domain/post/post.service.spec.ts

`GET /users/{userId}/posts` 시 연관관계를 가져오지 않는 이슈를 해결했습니다
innerJoin을 하지 않아 연관관계를 가져오지 않는 이슈였습니다.
- related #321 

GET /users/{userId}/posts 시 연관관계를 가져오지 않는 이슈를 해결했습니다

---

client/src/components/main/MainNav/NavContent/SearchContent/SearchContentHeader/SearchContentHeader.tsx
client/src/components/main/MainNav/NavContent/SearchContent/SearchHistoryView/SearchHistoryView.tsx
client/src/hooks/usePostInfiniteScroll.ts
client/src/mocks/handlers/searchHandler.ts

- 검색 요청 시 검색 창이 닫히도록 구현
- 검색 창이 열릴 때 history 요청하도록 구현
- 최적화를 진행하려다가 너무 오래 걸릴 것 같아서 일단 기능부터 붙였습니다.
- fix #347 

fix(FE): Search 요청이 완료된 이후 History 요청이 되지 않던 오류 해결 (#347)

---

server/src/domain/bookmark/bookmark.module.ts
server/src/domain/bookmark/bookmark.service.ts
server/src/domain/likes/likes.service.ts
server/src/domain/post/post.controller.ts

- 글 상세 조회 API에서 좋아요, 북마크 여부를 표시하도록 했습니다.
- 북마크 글 목록 API에서 좋아요 여부를 표시하도록 했습니다.
- related #361 

글 상세 조회, 북마크 글 목록 API에서 좋아요/북마크 여부 표시

---

client/src/apis/post.ts
client/src/components/main/PostScroll/Post/PostFooter/LeftBlockItems/BookmarkButton.tsx
client/src/components/main/PostScroll/Post/PostFooter/RightBlockItems/MoreButton.tsx
client/src/components/main/PostScroll/Post/PostFooter/RightBlockItems/PostMoreModal/PostMoreModal.tsx
client/src/hooks/useBookmark.ts
client/src/hooks/usePostInfiniteScroll.ts
client/src/hooks/usePostLike.ts
client/src/mocks/handlers/postHandler.ts
client/src/pages/Post/Post.tsx
client/src/store/useSearchStore.ts
client/src/types/modal.ts
client/src/types/search.ts

- 기존에 북마크 페이지에서 북마크를 해제하고 다시 검색 창으로 이동하는 등 페이지 전환 시 북마크가 갱신되지 않던 오류 발생
- 현재 보고 있는 스크롤바의 쿼리 키 : [QUERY_KEYS.POSTS, searchType, filter] 로 구성되어 있음.
- 북마크 갱신 mutation에 해당 쿼리 키를 명시해서 현재 보고 있는 화면에 대한 낙관적 업데이트 적용
- 오류가 발생했을 시 서버 상태가 변경되지 않았으므로 이전 상태로 롤백
- 갱신 성공 시 서버 상태가 변경되었으므로 다른 모든 스크롤바에 대해 업데이트 진행
- 로컬 mock환경에서 작동 확인
- fix #346 

fix(FE): 북마크 낙관적 업데이트가 페이지 전환 시 되지 않던 오류 수정 (#346)

---

scheduler-server/Dockerfile
server/Dockerfile

- 도커 컴포즈에 다음처럼 timezone 설정을 추가했는데 적용이 되지 않았습니다.
- 알아보니 경량 버전인 alpine에는 timezone 패키지가 없어서 설정이 적용되지 않기에, 도커 파일에 timezone 패키지를 설치하는 코드를 추가했습니다.
- related #363 

fix(BE): 도커 컨테이너에 timezone 패키지 설치 (#363)

---

scheduler-server/src/ranking/ranking.service.ts

- 기존 1시간동안 유지했던 인기 태그를 24시간동안 유지하도록 변경했습니다.
- related #392 

인기 태그를 24시간동안 유지하도록 변경했습니다.

---

.github/workflows/reusable-deployment-client.yml

- secrets 변수명이 틀려 인증이 제대로 되지 않던 오류를 수정했습니다.
- related #398 

클라이언트 CD 파일의 secrets 변수명 틀린 오류 수정

---

client/src/hooks/useLabel.ts
client/src/mocks/datasource/mockDataSource.ts
client/src/utils/queryString.ts

- encodeURI -> encodeURIComponent 사용하도록 변경
- 해시태그(#)는 그 뒤의 정보가 서버로 전송되지 않음
- fix #410 

fix(FE): URL에 해시태그가 있을 경우 주석처리되는 오류 해결 및 Mock 테스트 추가 (#410)

---

server/package-lock.json
server/package.json
server/src/domain/image/image.entity.ts
server/src/domain/image/image.repository.ts
server/src/domain/likes/likes.service.ts
server/src/domain/post/dto/controller-response.dto.ts
server/src/domain/post/dto/service-request.dto.ts
server/src/domain/post/post-search.service.spec.ts
server/src/domain/post/post-search.service.ts
server/src/domain/post/post.controller.ts
server/src/domain/post/post.entity.ts
server/src/domain/post/post.module.ts
server/src/domain/post/post.repository.ts
server/src/domain/post/post.service.spec.ts
server/src/domain/post/post.service.ts
server/src/domain/post/types/post-search-body.interface.ts
server/src/domain/review/review.service.ts
server/src/exception/post-input-invalid.exception.ts
server/src/exception/search-param-invalid.exception.ts
server/src/exception/search-response-invalid.exception.ts
server/src/exception/tag-invalid.exception.ts

검색의 효율성을 높여주는 Elastic Search를 적용하였습니다.
엘라스틱 서치의 효율을 높이기 위해 Post 엔티티에 역정규화를 진행하였습니다.
- 변경 전
- 변경 후
- 성능 변화 (데이터 50만개 기준)
- 조건 없이 최근 데이터만 가져올 때 (큰 차이 없음. 평균치 비슷하게 나옴)
- 조건을 사용 후, 검색 결과가 있을 때
- 조건을 사용 후, 검색 결과가 없을 때
- 고려해야 할 점
- DB가 분리되어 데이터 정합성이 깨질 수 있습니다. 따라서 Logstash를 사용해 배치 작업을 걸 계획입니다.
- 역정규화가 일어나 데이터 정합성이 깨질 수 있습니다. 스케쥴러를 통해 주기적으로 데이터 정합성을 맞출 계획입니다.
- related #377 

엘라스틱서치를 적용했습니다.

---

scheduler-server/src/ranking/ranking.controller.ts
scheduler-server/src/ranking/ranking.service.ts

- 랭킹이 24시간 유지되지 않던 오류를 수정했습니다.
- 랭킹에 시간 가중치를 적용했습니다.
- related #392 

랭킹 오류를 해결하고 랭킹에 시간 가중치를 적용했습니다.

---

server/src/domain/post/post-search.service.ts
server/src/domain/post/post.service.spec.ts
server/src/domain/post/post.service.ts

MySQL에서만 Post를 지우고, 엘라스틱서치에서는 적용하지 않아 발생한 이슈였습니다.
엘라스틱서치에서도 데이터를 지워 정합성을 맞춰줍니다.
삭제 이벤트가 발생하면 딜레이 없이 바로 삭제할 필요가 있다 생각해, 배치 작업을 걸지 않고 바로 삭제 이벤트를 적용시켜주었습니다.
- related #441 

엘라스틱서치 변경 후 Post가 삭제되지 않는 이슈를 해결하였습니다.

---

client/src/hooks/useNav.ts

URL이 이미 post/postId인 상태에서 다시 navigate 하는 동작이 일어나지 않는 것 같아서 메뉴를 눌러서 넘어갈 경우 URL을 /로 다시 돌려주는 기능 추가
- fix #420

fix(FE): 메뉴 버튼 클릭 시 / 로 네비게이션 되도록 오류 수정 (#420)

---

client/src/components/main/MainNav/NavMenus/BookmarkMenu/BookmarkMenu.tsx
client/src/hooks/useAuth.ts

- 기존 로직 : 미인증 상태에서 먼저 서버에 요청 -> 401응답과 함께 undeined 데이터 수신 -> 로그인 팝업-로그인 -> undefined 데이터로 포스트 정보 표시(오류)
- 수정 로직 : 미인증 상태에서는 로그인 요청-로그인 까지만 진행되고 실제 api호출이 가지 않도록 수정
- fix #420 

fix(FE): 미인증 상태에서 로그인 클릭 시 401 응답으로 출력하는 오류 수정 (#420)

---

server/src/domain/post/dto/controller-response.dto.ts

태그가 배열 안에 제대로 분리되지 않는 이슈를 해결하였습니다.
기존에 `["tag1","tag2"]`와 같이 반환되던 태그를 엘라스틱 서치 내부에서 `tag1 tag2` 방식으로 저장하도록 변경했고,
서버에서 제대로 파싱을 처리해주지 않아 다음과 같은 오류가 발생했습니다.
- related # 450

fix(BE): 태그들을 각 배열의 원소로 분리 (#450)

---

README.md
client/src/constants/search.ts
client/src/hooks/useSearch.ts

- README.md 사이에 공백을 누락한 오류를 해결했습니다.
- 태그 검색 시 5개까지 검색이 되는 조건을 추가했습니다.
- related #456 

v1.0.2 마이너 패치 - README.md 공백 작성, 검색 조건 태그 개수제한 적용 (#456)

---

server/src/domain/post/post-search.service.spec.ts
server/src/domain/post/post-search.service.ts
server/src/domain/post/post.entity.ts
server/src/domain/post/post.repository.ts

logstash에서 컬럼 이름들에 대문자가 사용할 수 없어, 엘라스틱서치에 컬럼 이름들을 소문자로 저장 했습니다.
이 과정에서 기존에 사용하던 `likeCount`, `reviewCount`가 검색 조건에 들어가, 검색이 제대로 되지 않았습니다.
`likecount`, `reviewcount`로 변경을 통해 문제를 해결하였습니다.
- related #465 

좋아요, 리뷰 개수로 검색이 가능하지 않던 이슈 해결하였습니다.
